name: HomePluginVeeThree
version: '3.0-BETA'
main: com.kasperskyy01.homePlugin
api-version: '1.21'

commands:
  sethome:
    description: "Set your home to the current location you are in"
    usage: "/home [home-name]"
    permission: sethome.use
  home:
    description: "Teleport to your home"
    usage: "/home [home-name]"
    permission: home.use
  delhome:
    description: "Delete a home"
    usage: "/delhome [home-name]"
    permission: delhome.use


permissions:
  sethome.use:
    description: "Allows usage of /sethome"
    default: true
  home.use:
    description: "Allows players to teleport to their homes"
    default: true
  delhome.use:
    description: "Allow players to delete their homes"
    default: true